////////////////////////////////////////////////////////////////////////////////
//
// @file          src/components/AiQuiz.tsx
// @description   Interactive AI-powered translation challenge
// @project       royal-scribe
// @author        Human: Developer | AI: Grok-4 (2025-11-18)
// @created       2025-11-18
// @modified      2025-11-18
// @version       1.1.0
// @license       MIT
// @tags          ui, ai, quiz
// @dependencies  react, lucide-react, zustand, HieroglyphRenderer
// @ai-generated  Yes
// @ai-model      Grok-4 (xAI)
//
// @changelog
// ──────────────────────────────────────────────────────────────────────────
// 1.1.0  (2025-11-18)  Updated challenge display to use HieroglyphRenderer
// 1.0.0  (2025-11-18)  Initial implementation
//
////////////////////////////////////////////////////////////////////////////////

import React, { useState, useEffect } from 'react';
import { useCaseStore } from '../store/useCaseStore';
import { ArrowLeft, Sparkles, Send, CheckCircle, XCircle, RefreshCcw, Loader2 } from 'lucide-react';
import { AiGrade } from '../../types';
import HieroglyphRenderer from './HieroglyphRenderer';

interface Props {
  onBack: () => void;
}

const AiQuiz: React.FC<Props> = ({ onBack }) => {
  const { currentAiChallenge, generateAiQuiz, submitAiQuizAnswer, clearAiQuiz, settings } = useCaseStore();
  
  const [userTranslation, setUserTranslation] = useState('');
  const [isGrading, setIsGrading] = useState(false);
  const [grade, setGrade] = useState<AiGrade | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);

  useEffect(() => {
    if (!currentAiChallenge) {
      handleGenerate();
    }
    return () => clearAiQuiz();
  }, []);

  const handleGenerate = async () => {
    setIsGenerating(true);
    setGrade(null);
    setUserTranslation('');
    await generateAiQuiz();
    setIsGenerating(false);
  };

  const handleSubmit = async () => {
    if (!userTranslation.trim()) return;
    setIsGrading(true);
    try {
      const result = await submitAiQuizAnswer(userTranslation);
      setGrade(result);
    } catch (error) {
      console.error("Grading failed", error);
    } finally {
      setIsGrading(false);
    }
  };

  if (isGenerating || !currentAiChallenge) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[50vh] space-y-6 animate-pulse">
         <div className="w-24 h-24 relative">
           <div className="absolute inset-0 border-4 border-egypt-gold/30 rounded-full animate-ping"></div>
           <div className="absolute inset-0 border-4 border-egypt-gold rounded-full flex items-center justify-center">
             <Sparkles className="text-egypt-gold" size={32} />
           </div>
         </div>
         <p className="font-serif text-egypt-gold text-lg tracking-widest uppercase">Consulting the Archives...</p>
         <p className="text-slate-500 text-sm">Generating a unique challenge based on your mastery.</p>
      </div>
    );
  }

  return (
    <div className="max-w-3xl mx-auto animate-in fade-in slide-in-from-bottom-4 duration-500">
       {/* Header */}
       <div className="flex items-center justify-between mb-8">
        <div className="flex items-center gap-4">
          <button onClick={onBack} className="p-2 rounded-full hover:bg-slate-800 text-slate-400 hover:text-white transition-colors">
             <ArrowLeft size={24} />
          </button>
          <div>
             <h2 className="text-2xl font-serif text-white flex items-center gap-2">
               <Sparkles className="text-egypt-gold" size={20} />
               Scribe's Challenge
             </h2>
             <p className="text-sm text-slate-500">Translate the phrase generated by the Oracle.</p>
          </div>
        </div>
      </div>

      {/* Challenge Card */}
      <div className="bg-egypt-paper border border-egypt-gold/40 rounded-xl shadow-2xl overflow-hidden relative">
         <div className="absolute inset-0 bg-grain opacity-10 pointer-events-none"></div>
         
         {/* Question Area */}
         <div className="p-10 text-center border-b border-slate-700/50 relative z-10">
            <div className="inline-block bg-black/10 px-4 py-1 rounded-full text-xs text-slate-500 uppercase tracking-wider mb-6 border border-black/5">
               Middle Egyptian Translation
            </div>
            
            <div className="mb-8">
              <HieroglyphRenderer 
                graftData={currentAiChallenge.hieroglyphs}
                size="jumbo"
                color="var(--color-text)"
                customScale={settings.glyphScale}
              />
            </div>
            
            <div className="text-xl font-serif italic text-egypt-gold/80 mb-2">
               {currentAiChallenge.transliteration}
            </div>
            
            <div className="text-xs text-slate-400 mt-6 flex items-center justify-center gap-2">
               <div className="w-1.5 h-1.5 rounded-full bg-egypt-gold"></div>
               {currentAiChallenge.context}
            </div>
         </div>

         {/* Answer Area */}
         <div className="p-8 bg-slate-900/50 relative z-10">
            {!grade ? (
              <div className="space-y-4">
                <label className="block text-sm font-bold text-slate-400 uppercase tracking-wider">Your Translation</label>
                <div className="relative">
                  <input 
                    type="text" 
                    value={userTranslation}
                    onChange={(e) => setUserTranslation(e.target.value)}
                    placeholder="Type the English meaning..."
                    className="w-full bg-black/40 border border-slate-600 rounded-lg px-4 py-4 text-white placeholder-slate-600 focus:border-egypt-gold outline-none font-serif text-lg pr-12 transition-all focus:shadow-[0_0_15px_rgba(197,160,89,0.1)]"
                    onKeyDown={(e) => e.key === 'Enter' && handleSubmit()}
                  />
                  <button 
                    onClick={handleSubmit}
                    disabled={isGrading || !userTranslation}
                    className={`absolute right-2 top-2 bottom-2 px-4 rounded-md flex items-center justify-center transition-all
                      ${!userTranslation ? 'text-slate-600 cursor-not-allowed' : 'bg-egypt-gold text-black hover:bg-yellow-500 shadow-lg'}
                    `}
                  >
                    {isGrading ? <Loader2 className="animate-spin" size={20} /> : <Send size={20} />}
                  </button>
                </div>
              </div>
            ) : (
              <div className="space-y-6 animate-in fade-in slide-in-from-bottom-2">
                 {/* Grade Badge */}
                 <div className={`flex items-center gap-4 p-4 rounded-lg border ${grade.isCorrect ? 'bg-green-900/20 border-green-500/30' : 'bg-red-900/20 border-red-500/30'}`}>
                    <div className={`p-3 rounded-full ${grade.isCorrect ? 'bg-green-500/20 text-green-500' : 'bg-red-500/20 text-red-500'}`}>
                       {grade.isCorrect ? <CheckCircle size={32} /> : <XCircle size={32} />}
                    </div>
                    <div className="flex-1">
                       <h4 className={`text-lg font-bold ${grade.isCorrect ? 'text-green-400' : 'text-red-400'}`}>
                         {grade.isCorrect ? 'Excellent Translation!' : 'Needs Improvement'}
                       </h4>
                       <div className="text-slate-300 text-sm mt-1">
                         Score: <span className="font-bold text-white">{grade.score}/100</span>
                       </div>
                    </div>
                 </div>

                 {/* Feedback */}
                 <div className="space-y-4">
                    <div>
                       <h5 className="text-xs text-slate-500 uppercase tracking-wider mb-1">Feedback</h5>
                       <p className="text-slate-300 leading-relaxed italic">"{grade.feedback}"</p>
                    </div>
                    
                    {!grade.isCorrect && (
                       <div>
                          <h5 className="text-xs text-slate-500 uppercase tracking-wider mb-1">Correct Meaning</h5>
                          <p className="text-egypt-gold font-serif text-lg">{currentAiChallenge.translation}</p>
                       </div>
                    )}
                 </div>

                 <button 
                   onClick={handleGenerate}
                   className="w-full py-3.5 bg-slate-800 hover:bg-egypt-gold hover:text-black text-white font-bold rounded-lg border border-slate-700 hover:border-egypt-gold transition-all flex items-center justify-center gap-2 shadow-lg"
                 >
                   <RefreshCcw size={18} /> Next Challenge
                 </button>
              </div>
            )}
         </div>
      </div>
    </div>
  );
};

export default AiQuiz;